name: Continuous Integration2

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test
    
jobs:
  build:
    name: Simple automatic test thru push inside of project folder
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm install
    - name: Test project
      run: npm test
