name: Github Actions Debug

on:
  pull-request:
  push:
    branches: 
      - main

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest
    env:
      working-directory: './continuous integration/survey-form-v2'
    steps:
    - name: Checkout code
      - uses: action/checkout@v2
    - name: Use Node.js
      - uses: action/setup-node@v2
    - name: Compose up the docker
      - run: docker-compose -f "docker-compose.yml" up -d --build
      - working-directory: ${{end.working-directory}}
    - name: Run tests from the built image
      - run: docker run survey-form sh -c "npm test"
      - working-directory: ${{end.working-directory}}
    - name: Compose down the docker
      - run: docker-compose -f "docker-compose.yml" down
      - working-directory: ${{end.working-directory}}
