name: Github Actions Example
on:
  push:
    branches: 
        - main
        - test
  pull_request:
    branches: 
      - main
      - test      
jobs:
  build:
    name: Build simple project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test