name: Github Actions Example
on:
  push:
    branches: 
        - main
        - test
  pull_request:
    branches: 
      - main
      - test      
jobs:
  build:
    name: Build simple project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies    
        run: npm ci
      - name: Test project
        run: npm test