name: Continuous Integration

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main
      - develop
    
jobs:
  build:
    name: Simple test thru PR
    runs-on: ubuntu-latest
    env:
      working-directory: './continuous integration/action_thru_pr'
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Test project
      run: npm test
      working-directory: ${{env.working-directory}}
