# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  #from build to action thru push (ATP)
  ATP:
    name: Build simple project
    runs-on: ubuntu-latest
    env:
      working-directory: './continuous integration/action_thru_push'
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Test project
      run: npm test
      working-directory: ${{env.working-directory}}
